name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # C++ проверки
    - name: Install C++ tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy cppcheck

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    
    - name: Run Clang-Tidy
      run: |
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-tidy -p build --
    
    - name: Run Cppcheck
      run: |
        cppcheck --enable=all --error-exitcode=1 .
    
    - name: Check formatting
      run: |
        clang-format --dry-run --Werror $(find . -name '*.cpp' -o -name '*.hpp')    

    # Shell скрипты
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
    
    - name: Run ShellCheck
      run: |
        find . -name '*.sh' -type f -exec shellcheck {} +

    # YAML файлы
    - name: Install yamllint
      run: |
        pip install yamllint
    
    - name: Run yamllint
      run: yamllint .

    # Dockerfile
    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0